---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version, synced with CI
    rev: v0.11.7
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]