site_name: Einops
repo_name: arogozhnikov/einops
repo_url: https://github.com/arogozhnikov/einops
site_url: https://einops.rocks
docs_dir: docs_src
theme:
  name: material
  favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/infinity
    repo: octicons/mark-github-16
nav:
  - Introduction: index.md
  - Tutorials:
      - Einops Basics: 1-einops-basics.ipynb
      - Einops for Deep Learning: 2-einops-for-deep-learning.ipynb
      - Einops.pack and unpack: 4-pack-and-unpack.ipynb
      - Einmix for great MLPs: 3-einmix-layer.ipynb
      - Pytorch: pytorch-examples.html
  - API Reference:
      - asnumpy: api/asnumpy.md
      - parse_shape: api/parse_shape.md
      - rearrange: api/rearrange.md
      - reduce: api/reduce.md
      - repeat: api/repeat.md
      - einsum: api/einsum.md
      - pack and unpack: api/pack_unpack.md
  - Testimonials: pages/testimonials.md
  - Community/Ecosystem: pages/projects.md
extra:
  search:
    language: en
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - markdown.extensions.md_in_html
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_options:
              warn_unknown_params: false
  - mkdocs-jupyter
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
  - css/mkdocs.css
  - css/codehilite.css