name: Deploy to pypi

on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install uv
              uses: astral-sh/setup-uv@v7
              with:
                  enable-cache: false

            - name: Publish einops to PyPi
              env:
                  UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
              run: |
                  uv build
                  uv publish
